python:
  - 3.10 # ['GITHUB_ACTIONS' not in os.environ]
  - 3.11 # ['GITHUB_ACTIONS' not in os.environ]
  - 3.12

c_compiler:    # [win]
- vs2022       # [win]
cxx_compiler:  # [win]
- vs2022       # [win]
